name:  ZebraTable
author:  davidwalsh
current:  1.0
category:  Interface
tags:  [tables,ui]
docs:  http://davidwalsh.name/mootools-zebra-table-plugin
demo:  http://davidwalsh.name/mootools-zebra-table-plugin